### PR TITLE
fix: send preparing connector status before `StartTransaction`

### PR DESCRIPTION
**Pull request by jerome-benoit**
closes #1031

### CODE REVIEW

**Comment by jerome-benoit** [comment]
@nahueld: could you please test that PR and it fix the issue?

**Comment by nahueld** [comment]
@jerome-benoit  works like a charm here are the logs:
```
debug: 4/10/2024, 6:00:01 PM bbqn0s1JfZvSBPJ5wuWc | << Command 'ReserveNow' received request payload: [2,"db353a91-f12d-48dc-9460-5a52c6318bdb","ReserveNow",{"expiryDate":"2024-04-10T21:59:00.000Z","reservationId":29,"connectorId":1,"idTag":"TLuwyyf5RrIrWwO15HSk"}]
debug: 4/10/2024, 6:00:01 PM bbqn0s1JfZvSBPJ5wuWc | >> Command 'Authorize' sent request payload: [2,"e5dc926d-79c7-487a-b0a8-0906e8d4dd4c","Authorize",{"idTag":"TLuwyyf5RrIrWwO15HSk"}]
debug: 4/10/2024, 6:00:01 PM bbqn0s1JfZvSBPJ5wuWc | << Command 'Authorize' received response payload: [3,"e5dc926d-79c7-487a-b0a8-0906e8d4dd4c",{"idTagInfo":{"parentIdTag":"TLuwyyf5RrIrWwO15HSk","status":"Accepted"}}]
debug: 4/10/2024, 6:00:01 PM bbqn0s1JfZvSBPJ5wuWc | idTag 'TLuwyyf5RrIrWwO15HSk' accepted on connector id 1
debug: 4/10/2024, 6:00:01 PM bbqn0s1JfZvSBPJ5wuWc | >> Command 'StatusNotification' sent request payload: [2,"8c1aa549-1825-4c70-898f-c7bbdc93ce48","StatusNotification",{"connectorId":1,"status":"Reserved","errorCode":"NoError"}]
debug: 4/10/2024, 6:00:01 PM bbqn0s1JfZvSBPJ5wuWc | << Command 'StatusNotification' received response payload: [3,"8c1aa549-1825-4c70-898f-c7bbdc93ce48",{}]
debug: 4/10/2024, 6:00:01 PM bbqn0s1JfZvSBPJ5wuWc | >> Command 'ReserveNow' sent response payload: [3,"db353a91-f12d-48dc-9460-5a52c6318bdb",{"status":"Accepted"}]

-------

debug: 4/10/2024, 6:00:11 PM bbqn0s1JfZvSBPJ5wuWc | >> Command 'StatusNotification' sent request payload: [2,"ea335ae0-05ce-422e-99b0-9a093b7c58d5","StatusNotification",{"connectorId":1,"status":"Preparing","errorCode":"NoError"}]
debug: 4/10/2024, 6:00:11 PM bbqn0s1JfZvSBPJ5wuWc | << Command 'StatusNotification' received response payload: [3,"ea335ae0-05ce-422e-99b0-9a093b7c58d5",{}]
debug: 4/10/2024, 6:00:11 PM bbqn0s1JfZvSBPJ5wuWc | >> Command 'StartTransaction' sent request payload: [2,"16adc7ad-7c4b-483b-9ea0-4f69528ecf29","StartTransaction",{"idTag":"TLuwyyf5RrIrWwO15HSk","meterStart":0,"timestamp":"2024-04-10T21:00:11.233Z","connectorId":1}]
debug: 4/10/2024, 6:00:11 PM bbqn0s1JfZvSBPJ5wuWc | << Command 'StartTransaction' received response payload: [3,"16adc7ad-7c4b-483b-9ea0-4f69528ecf29",{"transactionId":9,"idTagInfo":{"status":"Accepted"}}]
debug: 4/10/2024, 6:00:11 PM bbqn0s1JfZvSBPJ5wuWc | >> Command 'StatusNotification' sent request payload: [2,"0daf8a59-846d-4dcb-9041-566bb27854fe","StatusNotification",{"connectorId":1,"status":"Charging","errorCode":"NoError"}]
debug: 4/10/2024, 6:00:11 PM bbqn0s1JfZvSBPJ5wuWc | << Command 'StatusNotification' received response payload: [3,"0daf8a59-846d-4dcb-9041-566bb27854fe",{}]
info: 4/10/2024, 6:00:11 PM bbqn0s1JfZvSBPJ5wuWc | Transaction with id 9 STARTED on bbqn0s1JfZvSBPJ5wuWc#1 for idTag 'TLuwyyf5RrIrWwO15HSk'
debug: 4/10/2024, 6:00:18 PM bbqn0s1JfZvSBPJ5wuWc | Received a WS ping (rfc6455) from the server
debug: 4/10/2024, 6:00:19 PM qMUYbmJh7JiAr6567LwH | Received a WS ping (rfc6455) from the server
debug: 4/10/2024, 6:00:41 PM bbqn0s1JfZvSBPJ5wuWc | Trying to get MeterValues mea
```

**Comment by nahueld** [comment]
@jerome-benoit for some reason I noticed that the connector is no longer changing to Reserved, it stays in Available, in other words when you send the reserve request the status is not changed

**Comment by jerome-benoit** [comment]
> @jerome-benoit for some reason I noticed that the connector is no longer changing to Reserved, it stays in Available, in other words when you send the reserve request the status is not changed

That PR is not changing any code related to the `ReserveNow` incoming request handling. If a `ReserveNow` request is not changing the connector status despite 'ACCEPTED' response, it's not related to it and need to go in an issue with a detailed repro use case.

**Pull request merged**
